version: '3.8'

services:
  streamlit-app:
    build: .
    container_name: chatbot_openai_mistral
    ports:
      - "8501:8501"
    volumes:
      - ./downloaded_files:/app/downloaded_files
      - ./chromadb:/app/chromadb
      - ./datascience:/app/datascience
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_ENABLEXSRFPROTECTION=false
    restart: unless-stopped